### ISSUE TITLE
Why the sideways action?

### ISSUE THREAD

**Issue by daid** [tchapi/CuraForMakerbots#1]
I'm wondering, why didn't you just contact me 2 months ago? It's a few lines of code to add the changes so you no longer need a script:
https://github.com/Ultimaker/CuraEngine/commit/4f5b366af2548d3682d3c23f0a9fecf10d564431

(I'm not allowed to post in the MakerBot Opperators google group, which is a bit annoying. Does not mean I'm not willing to help out getting Cura up and running for MakerBot users)

**Comment by tchapi** [comment]
Hi @daid 
Well I just didn't have the time back then and needed a very quick solution, hence this little script — But now that you have the flavor in Cura itself, we're all good

Thanks !

**Comment by daid** [comment]
You're welcome. I'm going to release a version soon, and I would love to know if there are issues after that.
